FROM gcc:latest

RUN apt-get update && \
    apt-get install -y build-essential git protobuf-compiler
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        autoconf \
        automake \
        libtool \
        pkg-config \
        git \
        curl \
        ca-certificates \
        cmake \
        libprotobuf-dev \
        protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

# install protobuf from source
WORKDIR /dep
RUN git clone --recurse-submodules -b v3.21.1 https://github.com/protocolbuffers/protobuf.git && \
    cd ./protobuf && \
    git submodule update --init --recursive && \
    mkdir build && cd build && \
    cmake .. && \
    make -j2 && \
    make install && \
    ldconfig && \
    cd ../.. && rm -rf protobuf

# install protobuf-c from source
WORKDIR /dep
RUN git clone --recurse-submodules https://github.com/protobuf-c/protobuf-c.git && \
    cd ./protobuf-c && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install && \
    ldconfig

COPY . /quic-nfs
WORKDIR /quic-nfs
# build the mount and nfs servers
RUN make clean && \
    make all

# create a directory for export
RUN mkdir -p /nfs_share

CMD ["./tests/nfs/start_servers.sh"]