#!/bin/bash

# Clear dependencies
rm -rf ./deps/*
rmdir deps

# Basic packages
apt-get update && \
    apt-get install -y \
        build-essential \
        git \
        curl \
        libasan6 \
        libubsan1 \
        ca-certificates \
        autoconf \
        automake \
        libtool \
        pkg-config \
        cmake \
        openssl \
        libncurses-dev

# Install Criterion library for tests
apt-get install -y \
    libcriterion-dev

# Install Protobuf and Protobuf-C
apt-get install -y \
    protobuf-compiler \
    libprotobuf-dev \
    libprotobuf-c-dev \
    protobuf-c-compiler

# Install FUSE
apt-get install -y \
    fuse3 \
    libfuse3-dev

echo "protoc version:"
protoc --version

# Verify Protobuf installation
if ! command -v protoc &>/dev/null; then
    echo "Error: protoc is not installed."
    exit 1
fi

# Install libev for event loops
apt-get install -y \
    libev-dev

# Install Rust (needed for TQUIC)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
. "$HOME/.cargo/env"            # source cargo

# Verify Rust and Cargo installation
if ! command -v rustc &>/dev/null || ! command -v cargo &>/dev/null; then
    echo "Error: Rust or Cargo installation failed."
    exit 1
fi

# Install TQUIC from source
git clone https://github.com/tencent/tquic --recursive
mkdir deps
mv tquic ./deps                 # move TQUIC to 'dependencies' directory
cd ./deps/tquic
cargo build --release -F ffi

echo "Verifying installation..."
