FROM gcc:latest

ARG TRANSPORT_PROTOCOL
RUN echo "Building image with protocol: ${TRANSPORT_PROTOCOL}"
# only env vars can be used in CMD commands
ENV TRANSPORT_PROTOCOL=${TRANSPORT_PROTOCOL}

# copy the project directory
COPY . /quic-nfs

# install dependencies
WORKDIR /quic-nfs
RUN chmod +x ./install_dependencies && \
    ./install_dependencies

WORKDIR /quic-nfs
# create a directory for export
RUN mkdir -p /nfs_share && \
    chmod +rx /nfs_share
# mark /nfs_share as exported
RUN touch exports && \
    echo "/nfs_share *(rw)" > ./exports

# run the default command with 'exec' so it replaces the shell and gets signals (e.g. SIGTERM)
RUN chmod +x ./tests/docker_scripts/start_server
CMD ["/bin/bash", "-c", "exec ./tests/docker_scripts/start_server --proto=${TRANSPORT_PROTOCOL}"]