FROM gcc:latest

COPY . /quic-nfs
WORKDIR /quic-nfs

RUN chmod +x ./install_dependencies && \
    ./install_dependencies

WORKDIR /quic-nfs
# create a directory for export
RUN mkdir -p /nfs_share && \
    chmod +rx /nfs_share
# mark /nfs_share as exported
RUN touch exports && \
    echo "/nfs_share *(rw)" > ./exports

# create files and directories for procedure testing
RUN chmod +x ./tests/docker_scripts/setup_procedure_testing && \
    ./tests/docker_scripts/setup_procedure_testing

# create files and directories for testing of permission checking
RUN chmod +x ./tests/docker_scripts/setup_permission_testing && \
    ./tests/docker_scripts/setup_permission_testing


RUN chmod +x ./build/mount_and_nfs_server
CMD ["./build/mount_and_nfs_server", "--test"]