#!/bin/bash

# run the TCP server and tests

docker container rm -f mount-and-nfs-server-tcp
docker container rm -f mount-and-nfs-test-tcp
docker container rm -f mount-and-nfs-server-quic
docker container rm -f mount-and-nfs-test-quic
docker network rm nfs-test-net-quic
docker network rm nfs-test-net-tcp

docker network create --driver bridge --subnet 192.168.0.0/16 nfs-test-net-tcp

# start the server and give it time to set things up
docker run --detach --name mount-and-nfs-server-tcp \
    --network=nfs-test-net-tcp --ip=192.168.100.1 \
    --volume $(pwd)/src:/quic-nfs/src \
    --volume $(pwd)/tests:/quic-nfs/tests \
    --workdir /quic-nfs \
    mount-and-nfs-server-tcp:latest
sleep 10

# start the tests
docker run --name mount-and-nfs-test-tcp \
    --network=nfs-test-net-tcp --ip=192.168.100.2 \
    --volume $(pwd)/src:/quic-nfs/src \
    --volume $(pwd)/tests:/quic-nfs/tests \
    --workdir /quic-nfs \
    mount-and-nfs-test-tcp:latest
# save the exit code of the tests
TEST_EXIT_CODE=$?

# stop the server using SIGTERM
docker stop mount-and-nfs-server-tcp

# output all server logs (both stdout and stderr) to a file
mkdir -p ./logs
printf '##########################\n##########################\n TCP SERVER LOGS\n##########################\n##########################\n' > ./logs/mount_and_nfs_server_tcp_logs.txt
docker logs mount-and-nfs-server-tcp &>> ./logs/mount_and_nfs_server_tcp_logs.txt

# return tests exit code
exit $TEST_EXIT_CODE