/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: serialization/mount/mount.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "serialization/mount/mount.pb-c.h"
void   nfs__mount__empty__init
                     (Nfs__Mount__Empty         *message)
{
  static const Nfs__Mount__Empty init_value = NFS__MOUNT__EMPTY__INIT;
  *message = init_value;
}
size_t nfs__mount__empty__get_packed_size
                     (const Nfs__Mount__Empty *message)
{
  assert(message->base.descriptor == &nfs__mount__empty__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__empty__pack
                     (const Nfs__Mount__Empty *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__empty__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__empty__pack_to_buffer
                     (const Nfs__Mount__Empty *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__empty__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__Empty *
       nfs__mount__empty__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__Empty *)
     protobuf_c_message_unpack (&nfs__mount__empty__descriptor,
                                allocator, len, data);
}
void   nfs__mount__empty__free_unpacked
                     (Nfs__Mount__Empty *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__empty__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__fhandle__init
                     (Nfs__Mount__FHandle         *message)
{
  static const Nfs__Mount__FHandle init_value = NFS__MOUNT__FHANDLE__INIT;
  *message = init_value;
}
size_t nfs__mount__fhandle__get_packed_size
                     (const Nfs__Mount__FHandle *message)
{
  assert(message->base.descriptor == &nfs__mount__fhandle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__fhandle__pack
                     (const Nfs__Mount__FHandle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__fhandle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__fhandle__pack_to_buffer
                     (const Nfs__Mount__FHandle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__fhandle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__FHandle *
       nfs__mount__fhandle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__FHandle *)
     protobuf_c_message_unpack (&nfs__mount__fhandle__descriptor,
                                allocator, len, data);
}
void   nfs__mount__fhandle__free_unpacked
                     (Nfs__Mount__FHandle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__fhandle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__fh_status__init
                     (Nfs__Mount__FhStatus         *message)
{
  static const Nfs__Mount__FhStatus init_value = NFS__MOUNT__FH_STATUS__INIT;
  *message = init_value;
}
size_t nfs__mount__fh_status__get_packed_size
                     (const Nfs__Mount__FhStatus *message)
{
  assert(message->base.descriptor == &nfs__mount__fh_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__fh_status__pack
                     (const Nfs__Mount__FhStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__fh_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__fh_status__pack_to_buffer
                     (const Nfs__Mount__FhStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__fh_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__FhStatus *
       nfs__mount__fh_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__FhStatus *)
     protobuf_c_message_unpack (&nfs__mount__fh_status__descriptor,
                                allocator, len, data);
}
void   nfs__mount__fh_status__free_unpacked
                     (Nfs__Mount__FhStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__fh_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__dir_path__init
                     (Nfs__Mount__DirPath         *message)
{
  static const Nfs__Mount__DirPath init_value = NFS__MOUNT__DIR_PATH__INIT;
  *message = init_value;
}
size_t nfs__mount__dir_path__get_packed_size
                     (const Nfs__Mount__DirPath *message)
{
  assert(message->base.descriptor == &nfs__mount__dir_path__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__dir_path__pack
                     (const Nfs__Mount__DirPath *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__dir_path__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__dir_path__pack_to_buffer
                     (const Nfs__Mount__DirPath *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__dir_path__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__DirPath *
       nfs__mount__dir_path__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__DirPath *)
     protobuf_c_message_unpack (&nfs__mount__dir_path__descriptor,
                                allocator, len, data);
}
void   nfs__mount__dir_path__free_unpacked
                     (Nfs__Mount__DirPath *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__dir_path__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__name__init
                     (Nfs__Mount__Name         *message)
{
  static const Nfs__Mount__Name init_value = NFS__MOUNT__NAME__INIT;
  *message = init_value;
}
size_t nfs__mount__name__get_packed_size
                     (const Nfs__Mount__Name *message)
{
  assert(message->base.descriptor == &nfs__mount__name__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__name__pack
                     (const Nfs__Mount__Name *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__name__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__name__pack_to_buffer
                     (const Nfs__Mount__Name *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__name__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__Name *
       nfs__mount__name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__Name *)
     protobuf_c_message_unpack (&nfs__mount__name__descriptor,
                                allocator, len, data);
}
void   nfs__mount__name__free_unpacked
                     (Nfs__Mount__Name *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__name__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__mount_list__init
                     (Nfs__Mount__MountList         *message)
{
  static const Nfs__Mount__MountList init_value = NFS__MOUNT__MOUNT_LIST__INIT;
  *message = init_value;
}
size_t nfs__mount__mount_list__get_packed_size
                     (const Nfs__Mount__MountList *message)
{
  assert(message->base.descriptor == &nfs__mount__mount_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__mount_list__pack
                     (const Nfs__Mount__MountList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__mount_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__mount_list__pack_to_buffer
                     (const Nfs__Mount__MountList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__mount_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__MountList *
       nfs__mount__mount_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__MountList *)
     protobuf_c_message_unpack (&nfs__mount__mount_list__descriptor,
                                allocator, len, data);
}
void   nfs__mount__mount_list__free_unpacked
                     (Nfs__Mount__MountList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__mount_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__groups__init
                     (Nfs__Mount__Groups         *message)
{
  static const Nfs__Mount__Groups init_value = NFS__MOUNT__GROUPS__INIT;
  *message = init_value;
}
size_t nfs__mount__groups__get_packed_size
                     (const Nfs__Mount__Groups *message)
{
  assert(message->base.descriptor == &nfs__mount__groups__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__groups__pack
                     (const Nfs__Mount__Groups *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__groups__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__groups__pack_to_buffer
                     (const Nfs__Mount__Groups *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__groups__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__Groups *
       nfs__mount__groups__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__Groups *)
     protobuf_c_message_unpack (&nfs__mount__groups__descriptor,
                                allocator, len, data);
}
void   nfs__mount__groups__free_unpacked
                     (Nfs__Mount__Groups *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__groups__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__mount__export_list__init
                     (Nfs__Mount__ExportList         *message)
{
  static const Nfs__Mount__ExportList init_value = NFS__MOUNT__EXPORT_LIST__INIT;
  *message = init_value;
}
size_t nfs__mount__export_list__get_packed_size
                     (const Nfs__Mount__ExportList *message)
{
  assert(message->base.descriptor == &nfs__mount__export_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__mount__export_list__pack
                     (const Nfs__Mount__ExportList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__mount__export_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__mount__export_list__pack_to_buffer
                     (const Nfs__Mount__ExportList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__mount__export_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Mount__ExportList *
       nfs__mount__export_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Mount__ExportList *)
     protobuf_c_message_unpack (&nfs__mount__export_list__descriptor,
                                allocator, len, data);
}
void   nfs__mount__export_list__free_unpacked
                     (Nfs__Mount__ExportList *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__mount__export_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define nfs__mount__empty__field_descriptors NULL
#define nfs__mount__empty__field_indices_by_name NULL
#define nfs__mount__empty__number_ranges NULL
const ProtobufCMessageDescriptor nfs__mount__empty__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.Empty",
  "Empty",
  "Nfs__Mount__Empty",
  "nfs.mount",
  sizeof(Nfs__Mount__Empty),
  0,
  nfs__mount__empty__field_descriptors,
  nfs__mount__empty__field_indices_by_name,
  0,  nfs__mount__empty__number_ranges,
  (ProtobufCMessageInit) nfs__mount__empty__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__fhandle__field_descriptors[1] =
{
  {
    "handle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__FHandle, handle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__fhandle__field_indices_by_name[] = {
  0,   /* field[0] = handle */
};
static const ProtobufCIntRange nfs__mount__fhandle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__mount__fhandle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.FHandle",
  "FHandle",
  "Nfs__Mount__FHandle",
  "nfs.mount",
  sizeof(Nfs__Mount__FHandle),
  1,
  nfs__mount__fhandle__field_descriptors,
  nfs__mount__fhandle__field_indices_by_name,
  1,  nfs__mount__fhandle__number_ranges,
  (ProtobufCMessageInit) nfs__mount__fhandle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__fh_status__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__FhStatus, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "directory",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__FhStatus, directory),
    &nfs__mount__fhandle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__fh_status__field_indices_by_name[] = {
  1,   /* field[1] = directory */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nfs__mount__fh_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__mount__fh_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.FhStatus",
  "FhStatus",
  "Nfs__Mount__FhStatus",
  "nfs.mount",
  sizeof(Nfs__Mount__FhStatus),
  2,
  nfs__mount__fh_status__field_descriptors,
  nfs__mount__fh_status__field_indices_by_name,
  1,  nfs__mount__fh_status__number_ranges,
  (ProtobufCMessageInit) nfs__mount__fh_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__dir_path__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__DirPath, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__dir_path__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange nfs__mount__dir_path__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__mount__dir_path__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.DirPath",
  "DirPath",
  "Nfs__Mount__DirPath",
  "nfs.mount",
  sizeof(Nfs__Mount__DirPath),
  1,
  nfs__mount__dir_path__field_descriptors,
  nfs__mount__dir_path__field_indices_by_name,
  1,  nfs__mount__dir_path__number_ranges,
  (ProtobufCMessageInit) nfs__mount__dir_path__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__name__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__Name, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__name__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange nfs__mount__name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__mount__name__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.Name",
  "Name",
  "Nfs__Mount__Name",
  "nfs.mount",
  sizeof(Nfs__Mount__Name),
  1,
  nfs__mount__name__field_descriptors,
  nfs__mount__name__field_indices_by_name,
  1,  nfs__mount__name__number_ranges,
  (ProtobufCMessageInit) nfs__mount__name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__mount_list__field_descriptors[3] =
{
  {
    "hostname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__MountList, hostname),
    &nfs__mount__name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "directory",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__MountList, directory),
    &nfs__mount__dir_path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nextentry",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__MountList, nextentry),
    &nfs__mount__mount_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__mount_list__field_indices_by_name[] = {
  1,   /* field[1] = directory */
  0,   /* field[0] = hostname */
  2,   /* field[2] = nextentry */
};
static const ProtobufCIntRange nfs__mount__mount_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__mount__mount_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.MountList",
  "MountList",
  "Nfs__Mount__MountList",
  "nfs.mount",
  sizeof(Nfs__Mount__MountList),
  3,
  nfs__mount__mount_list__field_descriptors,
  nfs__mount__mount_list__field_indices_by_name,
  1,  nfs__mount__mount_list__number_ranges,
  (ProtobufCMessageInit) nfs__mount__mount_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__groups__field_descriptors[2] =
{
  {
    "grname",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__Groups, grname),
    &nfs__mount__name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "grnext",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__Groups, grnext),
    &nfs__mount__groups__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__groups__field_indices_by_name[] = {
  0,   /* field[0] = grname */
  1,   /* field[1] = grnext */
};
static const ProtobufCIntRange nfs__mount__groups__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__mount__groups__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.Groups",
  "Groups",
  "Nfs__Mount__Groups",
  "nfs.mount",
  sizeof(Nfs__Mount__Groups),
  2,
  nfs__mount__groups__field_descriptors,
  nfs__mount__groups__field_indices_by_name,
  1,  nfs__mount__groups__number_ranges,
  (ProtobufCMessageInit) nfs__mount__groups__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__mount__export_list__field_descriptors[3] =
{
  {
    "filesys",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__ExportList, filesys),
    &nfs__mount__dir_path__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "groups",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__ExportList, groups),
    &nfs__mount__groups__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "next",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__Mount__ExportList, next),
    &nfs__mount__export_list__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__mount__export_list__field_indices_by_name[] = {
  0,   /* field[0] = filesys */
  1,   /* field[1] = groups */
  2,   /* field[2] = next */
};
static const ProtobufCIntRange nfs__mount__export_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__mount__export_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.mount.ExportList",
  "ExportList",
  "Nfs__Mount__ExportList",
  "nfs.mount",
  sizeof(Nfs__Mount__ExportList),
  3,
  nfs__mount__export_list__field_descriptors,
  nfs__mount__export_list__field_indices_by_name,
  1,  nfs__mount__export_list__number_ranges,
  (ProtobufCMessageInit) nfs__mount__export_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
