/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/serialization/nfs/nfs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "src/serialization/nfs/nfs.pb-c.h"
void   nfs__fhandle__init
                     (Nfs__FHandle         *message)
{
  static const Nfs__FHandle init_value = NFS__FHANDLE__INIT;
  *message = init_value;
}
size_t nfs__fhandle__get_packed_size
                     (const Nfs__FHandle *message)
{
  assert(message->base.descriptor == &nfs__fhandle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__fhandle__pack
                     (const Nfs__FHandle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__fhandle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__fhandle__pack_to_buffer
                     (const Nfs__FHandle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__fhandle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__FHandle *
       nfs__fhandle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__FHandle *)
     protobuf_c_message_unpack (&nfs__fhandle__descriptor,
                                allocator, len, data);
}
void   nfs__fhandle__free_unpacked
                     (Nfs__FHandle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__fhandle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__time_val__init
                     (Nfs__TimeVal         *message)
{
  static const Nfs__TimeVal init_value = NFS__TIME_VAL__INIT;
  *message = init_value;
}
size_t nfs__time_val__get_packed_size
                     (const Nfs__TimeVal *message)
{
  assert(message->base.descriptor == &nfs__time_val__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__time_val__pack
                     (const Nfs__TimeVal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__time_val__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__time_val__pack_to_buffer
                     (const Nfs__TimeVal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__time_val__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__TimeVal *
       nfs__time_val__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__TimeVal *)
     protobuf_c_message_unpack (&nfs__time_val__descriptor,
                                allocator, len, data);
}
void   nfs__time_val__free_unpacked
                     (Nfs__TimeVal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__time_val__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__fattr__init
                     (Nfs__FAttr         *message)
{
  static const Nfs__FAttr init_value = NFS__FATTR__INIT;
  *message = init_value;
}
size_t nfs__fattr__get_packed_size
                     (const Nfs__FAttr *message)
{
  assert(message->base.descriptor == &nfs__fattr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__fattr__pack
                     (const Nfs__FAttr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__fattr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__fattr__pack_to_buffer
                     (const Nfs__FAttr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__fattr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__FAttr *
       nfs__fattr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__FAttr *)
     protobuf_c_message_unpack (&nfs__fattr__descriptor,
                                allocator, len, data);
}
void   nfs__fattr__free_unpacked
                     (Nfs__FAttr *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__fattr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__sattr__init
                     (Nfs__SAttr         *message)
{
  static const Nfs__SAttr init_value = NFS__SATTR__INIT;
  *message = init_value;
}
size_t nfs__sattr__get_packed_size
                     (const Nfs__SAttr *message)
{
  assert(message->base.descriptor == &nfs__sattr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__sattr__pack
                     (const Nfs__SAttr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__sattr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__sattr__pack_to_buffer
                     (const Nfs__SAttr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__sattr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__SAttr *
       nfs__sattr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__SAttr *)
     protobuf_c_message_unpack (&nfs__sattr__descriptor,
                                allocator, len, data);
}
void   nfs__sattr__free_unpacked
                     (Nfs__SAttr *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__sattr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__file_name__init
                     (Nfs__FileName         *message)
{
  static const Nfs__FileName init_value = NFS__FILE_NAME__INIT;
  *message = init_value;
}
size_t nfs__file_name__get_packed_size
                     (const Nfs__FileName *message)
{
  assert(message->base.descriptor == &nfs__file_name__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__file_name__pack
                     (const Nfs__FileName *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__file_name__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__file_name__pack_to_buffer
                     (const Nfs__FileName *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__file_name__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__FileName *
       nfs__file_name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__FileName *)
     protobuf_c_message_unpack (&nfs__file_name__descriptor,
                                allocator, len, data);
}
void   nfs__file_name__free_unpacked
                     (Nfs__FileName *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__file_name__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__path__init
                     (Nfs__Path         *message)
{
  static const Nfs__Path init_value = NFS__PATH__INIT;
  *message = init_value;
}
size_t nfs__path__get_packed_size
                     (const Nfs__Path *message)
{
  assert(message->base.descriptor == &nfs__path__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__path__pack
                     (const Nfs__Path *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__path__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__path__pack_to_buffer
                     (const Nfs__Path *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__path__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__Path *
       nfs__path__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__Path *)
     protobuf_c_message_unpack (&nfs__path__descriptor,
                                allocator, len, data);
}
void   nfs__path__free_unpacked
                     (Nfs__Path *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__path__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__attr_stat__init
                     (Nfs__AttrStat         *message)
{
  static const Nfs__AttrStat init_value = NFS__ATTR_STAT__INIT;
  *message = init_value;
}
size_t nfs__attr_stat__get_packed_size
                     (const Nfs__AttrStat *message)
{
  assert(message->base.descriptor == &nfs__attr_stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__attr_stat__pack
                     (const Nfs__AttrStat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__attr_stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__attr_stat__pack_to_buffer
                     (const Nfs__AttrStat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__attr_stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__AttrStat *
       nfs__attr_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__AttrStat *)
     protobuf_c_message_unpack (&nfs__attr_stat__descriptor,
                                allocator, len, data);
}
void   nfs__attr_stat__free_unpacked
                     (Nfs__AttrStat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__attr_stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__dir_op_args__init
                     (Nfs__DirOpArgs         *message)
{
  static const Nfs__DirOpArgs init_value = NFS__DIR_OP_ARGS__INIT;
  *message = init_value;
}
size_t nfs__dir_op_args__get_packed_size
                     (const Nfs__DirOpArgs *message)
{
  assert(message->base.descriptor == &nfs__dir_op_args__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__dir_op_args__pack
                     (const Nfs__DirOpArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__dir_op_args__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__dir_op_args__pack_to_buffer
                     (const Nfs__DirOpArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__dir_op_args__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__DirOpArgs *
       nfs__dir_op_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__DirOpArgs *)
     protobuf_c_message_unpack (&nfs__dir_op_args__descriptor,
                                allocator, len, data);
}
void   nfs__dir_op_args__free_unpacked
                     (Nfs__DirOpArgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__dir_op_args__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__dir_op_ok__init
                     (Nfs__DirOpOk         *message)
{
  static const Nfs__DirOpOk init_value = NFS__DIR_OP_OK__INIT;
  *message = init_value;
}
size_t nfs__dir_op_ok__get_packed_size
                     (const Nfs__DirOpOk *message)
{
  assert(message->base.descriptor == &nfs__dir_op_ok__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__dir_op_ok__pack
                     (const Nfs__DirOpOk *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__dir_op_ok__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__dir_op_ok__pack_to_buffer
                     (const Nfs__DirOpOk *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__dir_op_ok__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__DirOpOk *
       nfs__dir_op_ok__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__DirOpOk *)
     protobuf_c_message_unpack (&nfs__dir_op_ok__descriptor,
                                allocator, len, data);
}
void   nfs__dir_op_ok__free_unpacked
                     (Nfs__DirOpOk *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__dir_op_ok__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__dir_op_res__init
                     (Nfs__DirOpRes         *message)
{
  static const Nfs__DirOpRes init_value = NFS__DIR_OP_RES__INIT;
  *message = init_value;
}
size_t nfs__dir_op_res__get_packed_size
                     (const Nfs__DirOpRes *message)
{
  assert(message->base.descriptor == &nfs__dir_op_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__dir_op_res__pack
                     (const Nfs__DirOpRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__dir_op_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__dir_op_res__pack_to_buffer
                     (const Nfs__DirOpRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__dir_op_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__DirOpRes *
       nfs__dir_op_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__DirOpRes *)
     protobuf_c_message_unpack (&nfs__dir_op_res__descriptor,
                                allocator, len, data);
}
void   nfs__dir_op_res__free_unpacked
                     (Nfs__DirOpRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__dir_op_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__sattr_args__init
                     (Nfs__SAttrArgs         *message)
{
  static const Nfs__SAttrArgs init_value = NFS__SATTR_ARGS__INIT;
  *message = init_value;
}
size_t nfs__sattr_args__get_packed_size
                     (const Nfs__SAttrArgs *message)
{
  assert(message->base.descriptor == &nfs__sattr_args__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__sattr_args__pack
                     (const Nfs__SAttrArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__sattr_args__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__sattr_args__pack_to_buffer
                     (const Nfs__SAttrArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__sattr_args__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__SAttrArgs *
       nfs__sattr_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__SAttrArgs *)
     protobuf_c_message_unpack (&nfs__sattr_args__descriptor,
                                allocator, len, data);
}
void   nfs__sattr_args__free_unpacked
                     (Nfs__SAttrArgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__sattr_args__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__read_link_res__init
                     (Nfs__ReadLinkRes         *message)
{
  static const Nfs__ReadLinkRes init_value = NFS__READ_LINK_RES__INIT;
  *message = init_value;
}
size_t nfs__read_link_res__get_packed_size
                     (const Nfs__ReadLinkRes *message)
{
  assert(message->base.descriptor == &nfs__read_link_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__read_link_res__pack
                     (const Nfs__ReadLinkRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__read_link_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__read_link_res__pack_to_buffer
                     (const Nfs__ReadLinkRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__read_link_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__ReadLinkRes *
       nfs__read_link_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__ReadLinkRes *)
     protobuf_c_message_unpack (&nfs__read_link_res__descriptor,
                                allocator, len, data);
}
void   nfs__read_link_res__free_unpacked
                     (Nfs__ReadLinkRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__read_link_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__read_args__init
                     (Nfs__ReadArgs         *message)
{
  static const Nfs__ReadArgs init_value = NFS__READ_ARGS__INIT;
  *message = init_value;
}
size_t nfs__read_args__get_packed_size
                     (const Nfs__ReadArgs *message)
{
  assert(message->base.descriptor == &nfs__read_args__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__read_args__pack
                     (const Nfs__ReadArgs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__read_args__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__read_args__pack_to_buffer
                     (const Nfs__ReadArgs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__read_args__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__ReadArgs *
       nfs__read_args__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__ReadArgs *)
     protobuf_c_message_unpack (&nfs__read_args__descriptor,
                                allocator, len, data);
}
void   nfs__read_args__free_unpacked
                     (Nfs__ReadArgs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__read_args__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__read_res_body__init
                     (Nfs__ReadResBody         *message)
{
  static const Nfs__ReadResBody init_value = NFS__READ_RES_BODY__INIT;
  *message = init_value;
}
size_t nfs__read_res_body__get_packed_size
                     (const Nfs__ReadResBody *message)
{
  assert(message->base.descriptor == &nfs__read_res_body__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__read_res_body__pack
                     (const Nfs__ReadResBody *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__read_res_body__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__read_res_body__pack_to_buffer
                     (const Nfs__ReadResBody *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__read_res_body__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__ReadResBody *
       nfs__read_res_body__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__ReadResBody *)
     protobuf_c_message_unpack (&nfs__read_res_body__descriptor,
                                allocator, len, data);
}
void   nfs__read_res_body__free_unpacked
                     (Nfs__ReadResBody *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__read_res_body__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   nfs__read_res__init
                     (Nfs__ReadRes         *message)
{
  static const Nfs__ReadRes init_value = NFS__READ_RES__INIT;
  *message = init_value;
}
size_t nfs__read_res__get_packed_size
                     (const Nfs__ReadRes *message)
{
  assert(message->base.descriptor == &nfs__read_res__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nfs__read_res__pack
                     (const Nfs__ReadRes *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nfs__read_res__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nfs__read_res__pack_to_buffer
                     (const Nfs__ReadRes *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nfs__read_res__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Nfs__ReadRes *
       nfs__read_res__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Nfs__ReadRes *)
     protobuf_c_message_unpack (&nfs__read_res__descriptor,
                                allocator, len, data);
}
void   nfs__read_res__free_unpacked
                     (Nfs__ReadRes *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nfs__read_res__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nfs__fhandle__field_descriptors[1] =
{
  {
    "nfs_filehandle",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__FHandle, nfs_filehandle),
    &nfs_fh__nfs_file_handle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__fhandle__field_indices_by_name[] = {
  0,   /* field[0] = nfs_filehandle */
};
static const ProtobufCIntRange nfs__fhandle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__fhandle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.FHandle",
  "FHandle",
  "Nfs__FHandle",
  "nfs",
  sizeof(Nfs__FHandle),
  1,
  nfs__fhandle__field_descriptors,
  nfs__fhandle__field_indices_by_name,
  1,  nfs__fhandle__number_ranges,
  (ProtobufCMessageInit) nfs__fhandle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__time_val__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__TimeVal, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "useconds",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__TimeVal, useconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__time_val__field_indices_by_name[] = {
  0,   /* field[0] = seconds */
  1,   /* field[1] = useconds */
};
static const ProtobufCIntRange nfs__time_val__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__time_val__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.TimeVal",
  "TimeVal",
  "Nfs__TimeVal",
  "nfs",
  sizeof(Nfs__TimeVal),
  2,
  nfs__time_val__field_descriptors,
  nfs__time_val__field_indices_by_name,
  1,  nfs__time_val__number_ranges,
  (ProtobufCMessageInit) nfs__time_val__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__fattr__field_descriptors[14] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, type),
    &nfs__ftype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nlink",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, nlink),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blocksize",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, blocksize),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rdev",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, rdev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blocks",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, blocks),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fsid",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, fsid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fileid",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, fileid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atime",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, atime),
    &nfs__time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtime",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, mtime),
    &nfs__time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ctime",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__FAttr, ctime),
    &nfs__time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__fattr__field_indices_by_name[] = {
  11,   /* field[11] = atime */
  8,   /* field[8] = blocks */
  6,   /* field[6] = blocksize */
  13,   /* field[13] = ctime */
  10,   /* field[10] = fileid */
  9,   /* field[9] = fsid */
  4,   /* field[4] = gid */
  1,   /* field[1] = mode */
  12,   /* field[12] = mtime */
  2,   /* field[2] = nlink */
  7,   /* field[7] = rdev */
  5,   /* field[5] = size */
  0,   /* field[0] = type */
  3,   /* field[3] = uid */
};
static const ProtobufCIntRange nfs__fattr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor nfs__fattr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.FAttr",
  "FAttr",
  "Nfs__FAttr",
  "nfs",
  sizeof(Nfs__FAttr),
  14,
  nfs__fattr__field_descriptors,
  nfs__fattr__field_indices_by_name,
  1,  nfs__fattr__number_ranges,
  (ProtobufCMessageInit) nfs__fattr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__sattr__field_descriptors[6] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atime",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, atime),
    &nfs__time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtime",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttr, mtime),
    &nfs__time_val__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__sattr__field_indices_by_name[] = {
  4,   /* field[4] = atime */
  2,   /* field[2] = gid */
  0,   /* field[0] = mode */
  5,   /* field[5] = mtime */
  3,   /* field[3] = size */
  1,   /* field[1] = uid */
};
static const ProtobufCIntRange nfs__sattr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor nfs__sattr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.SAttr",
  "SAttr",
  "Nfs__SAttr",
  "nfs",
  sizeof(Nfs__SAttr),
  6,
  nfs__sattr__field_descriptors,
  nfs__sattr__field_indices_by_name,
  1,  nfs__sattr__number_ranges,
  (ProtobufCMessageInit) nfs__sattr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__file_name__field_descriptors[1] =
{
  {
    "filename",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nfs__FileName, filename),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__file_name__field_indices_by_name[] = {
  0,   /* field[0] = filename */
};
static const ProtobufCIntRange nfs__file_name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__file_name__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.FileName",
  "FileName",
  "Nfs__FileName",
  "nfs",
  sizeof(Nfs__FileName),
  1,
  nfs__file_name__field_descriptors,
  nfs__file_name__field_indices_by_name,
  1,  nfs__file_name__number_ranges,
  (ProtobufCMessageInit) nfs__file_name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__path__field_descriptors[1] =
{
  {
    "path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Nfs__Path, path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__path__field_indices_by_name[] = {
  0,   /* field[0] = path */
};
static const ProtobufCIntRange nfs__path__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nfs__path__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.Path",
  "Path",
  "Nfs__Path",
  "nfs",
  sizeof(Nfs__Path),
  1,
  nfs__path__field_descriptors,
  nfs__path__field_indices_by_name,
  1,  nfs__path__number_ranges,
  (ProtobufCMessageInit) nfs__path__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__attr_stat__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Nfs__AttrStat, status),
    &nfs__stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__AttrStat, body_case),
    offsetof(Nfs__AttrStat, attributes),
    &nfs__fattr__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_case",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__AttrStat, body_case),
    offsetof(Nfs__AttrStat, default_case),
    &google__protobuf__empty__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__attr_stat__field_indices_by_name[] = {
  1,   /* field[1] = attributes */
  2,   /* field[2] = default_case */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nfs__attr_stat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__attr_stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.AttrStat",
  "AttrStat",
  "Nfs__AttrStat",
  "nfs",
  sizeof(Nfs__AttrStat),
  3,
  nfs__attr_stat__field_descriptors,
  nfs__attr_stat__field_indices_by_name,
  1,  nfs__attr_stat__number_ranges,
  (ProtobufCMessageInit) nfs__attr_stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__dir_op_args__field_descriptors[2] =
{
  {
    "dir",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__DirOpArgs, dir),
    &nfs__fhandle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__DirOpArgs, name),
    &nfs__file_name__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__dir_op_args__field_indices_by_name[] = {
  0,   /* field[0] = dir */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange nfs__dir_op_args__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__dir_op_args__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.DirOpArgs",
  "DirOpArgs",
  "Nfs__DirOpArgs",
  "nfs",
  sizeof(Nfs__DirOpArgs),
  2,
  nfs__dir_op_args__field_descriptors,
  nfs__dir_op_args__field_indices_by_name,
  1,  nfs__dir_op_args__number_ranges,
  (ProtobufCMessageInit) nfs__dir_op_args__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__dir_op_ok__field_descriptors[2] =
{
  {
    "file",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__DirOpOk, file),
    &nfs__fhandle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__DirOpOk, attributes),
    &nfs__fattr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__dir_op_ok__field_indices_by_name[] = {
  1,   /* field[1] = attributes */
  0,   /* field[0] = file */
};
static const ProtobufCIntRange nfs__dir_op_ok__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__dir_op_ok__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.DirOpOk",
  "DirOpOk",
  "Nfs__DirOpOk",
  "nfs",
  sizeof(Nfs__DirOpOk),
  2,
  nfs__dir_op_ok__field_descriptors,
  nfs__dir_op_ok__field_indices_by_name,
  1,  nfs__dir_op_ok__number_ranges,
  (ProtobufCMessageInit) nfs__dir_op_ok__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__dir_op_res__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Nfs__DirOpRes, status),
    &nfs__stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diropok",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__DirOpRes, body_case),
    offsetof(Nfs__DirOpRes, diropok),
    &nfs__dir_op_ok__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_case",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__DirOpRes, body_case),
    offsetof(Nfs__DirOpRes, default_case),
    &google__protobuf__empty__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__dir_op_res__field_indices_by_name[] = {
  2,   /* field[2] = default_case */
  1,   /* field[1] = diropok */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nfs__dir_op_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__dir_op_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.DirOpRes",
  "DirOpRes",
  "Nfs__DirOpRes",
  "nfs",
  sizeof(Nfs__DirOpRes),
  3,
  nfs__dir_op_res__field_descriptors,
  nfs__dir_op_res__field_indices_by_name,
  1,  nfs__dir_op_res__number_ranges,
  (ProtobufCMessageInit) nfs__dir_op_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__sattr_args__field_descriptors[2] =
{
  {
    "file",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttrArgs, file),
    &nfs__fhandle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__SAttrArgs, attributes),
    &nfs__sattr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__sattr_args__field_indices_by_name[] = {
  1,   /* field[1] = attributes */
  0,   /* field[0] = file */
};
static const ProtobufCIntRange nfs__sattr_args__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__sattr_args__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.SAttrArgs",
  "SAttrArgs",
  "Nfs__SAttrArgs",
  "nfs",
  sizeof(Nfs__SAttrArgs),
  2,
  nfs__sattr_args__field_descriptors,
  nfs__sattr_args__field_indices_by_name,
  1,  nfs__sattr_args__number_ranges,
  (ProtobufCMessageInit) nfs__sattr_args__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__read_link_res__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadLinkRes, status),
    &nfs__stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__ReadLinkRes, body_case),
    offsetof(Nfs__ReadLinkRes, data),
    &nfs__path__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_case",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__ReadLinkRes, body_case),
    offsetof(Nfs__ReadLinkRes, default_case),
    &google__protobuf__empty__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__read_link_res__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = default_case */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nfs__read_link_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__read_link_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.ReadLinkRes",
  "ReadLinkRes",
  "Nfs__ReadLinkRes",
  "nfs",
  sizeof(Nfs__ReadLinkRes),
  3,
  nfs__read_link_res__field_descriptors,
  nfs__read_link_res__field_indices_by_name,
  1,  nfs__read_link_res__number_ranges,
  (ProtobufCMessageInit) nfs__read_link_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__read_args__field_descriptors[4] =
{
  {
    "file",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadArgs, file),
    &nfs__fhandle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadArgs, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadArgs, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "totalcount",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadArgs, totalcount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__read_args__field_indices_by_name[] = {
  2,   /* field[2] = count */
  0,   /* field[0] = file */
  1,   /* field[1] = offset */
  3,   /* field[3] = totalcount */
};
static const ProtobufCIntRange nfs__read_args__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor nfs__read_args__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.ReadArgs",
  "ReadArgs",
  "Nfs__ReadArgs",
  "nfs",
  sizeof(Nfs__ReadArgs),
  4,
  nfs__read_args__field_descriptors,
  nfs__read_args__field_indices_by_name,
  1,  nfs__read_args__number_ranges,
  (ProtobufCMessageInit) nfs__read_args__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__read_res_body__field_descriptors[2] =
{
  {
    "attributes",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadResBody, attributes),
    &nfs__fattr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadResBody, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__read_res_body__field_indices_by_name[] = {
  0,   /* field[0] = attributes */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange nfs__read_res_body__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor nfs__read_res_body__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.ReadResBody",
  "ReadResBody",
  "Nfs__ReadResBody",
  "nfs",
  sizeof(Nfs__ReadResBody),
  2,
  nfs__read_res_body__field_descriptors,
  nfs__read_res_body__field_indices_by_name,
  1,  nfs__read_res_body__number_ranges,
  (ProtobufCMessageInit) nfs__read_res_body__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor nfs__read_res__field_descriptors[3] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Nfs__ReadRes, status),
    &nfs__stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nfsdata",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__ReadRes, body_case),
    offsetof(Nfs__ReadRes, nfsdata),
    &nfs__read_res_body__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_case",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Nfs__ReadRes, body_case),
    offsetof(Nfs__ReadRes, default_case),
    &google__protobuf__empty__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nfs__read_res__field_indices_by_name[] = {
  2,   /* field[2] = default_case */
  1,   /* field[1] = nfsdata */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange nfs__read_res__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor nfs__read_res__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "nfs.ReadRes",
  "ReadRes",
  "Nfs__ReadRes",
  "nfs",
  sizeof(Nfs__ReadRes),
  3,
  nfs__read_res__field_descriptors,
  nfs__read_res__field_indices_by_name,
  1,  nfs__read_res__number_ranges,
  (ProtobufCMessageInit) nfs__read_res__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nfs__stat__enum_values_by_number[18] =
{
  { "NFS_OK", "NFS__STAT__NFS_OK", 0 },
  { "NFSERR_PERM", "NFS__STAT__NFSERR_PERM", 1 },
  { "NFSERR_NOENT", "NFS__STAT__NFSERR_NOENT", 2 },
  { "NFSERR_IO", "NFS__STAT__NFSERR_IO", 5 },
  { "NFSERR_NXIO", "NFS__STAT__NFSERR_NXIO", 6 },
  { "NFSERR_ACCES", "NFS__STAT__NFSERR_ACCES", 13 },
  { "NFSERR_EXIST", "NFS__STAT__NFSERR_EXIST", 17 },
  { "NFSERR_NODEV", "NFS__STAT__NFSERR_NODEV", 19 },
  { "NFSERR_NOTDIR", "NFS__STAT__NFSERR_NOTDIR", 20 },
  { "NFSERR_ISDIR", "NFS__STAT__NFSERR_ISDIR", 21 },
  { "NFSERR_FBIG", "NFS__STAT__NFSERR_FBIG", 27 },
  { "NFSERR_NOSPC", "NFS__STAT__NFSERR_NOSPC", 28 },
  { "NFSERR_ROFS", "NFS__STAT__NFSERR_ROFS", 30 },
  { "NFSERR_NAMETOOLONG", "NFS__STAT__NFSERR_NAMETOOLONG", 63 },
  { "NFSERR_NOTEMPTY", "NFS__STAT__NFSERR_NOTEMPTY", 66 },
  { "NFSERR_DQUOT", "NFS__STAT__NFSERR_DQUOT", 69 },
  { "NFSERR_STALE", "NFS__STAT__NFSERR_STALE", 70 },
  { "NFSERR_WFLUSH", "NFS__STAT__NFSERR_WFLUSH", 99 },
};
static const ProtobufCIntRange nfs__stat__value_ranges[] = {
{0, 0},{5, 3},{13, 5},{17, 6},{19, 7},{27, 10},{30, 12},{63, 13},{66, 14},{69, 15},{99, 17},{0, 18}
};
static const ProtobufCEnumValueIndex nfs__stat__enum_values_by_name[18] =
{
  { "NFSERR_ACCES", 5 },
  { "NFSERR_DQUOT", 15 },
  { "NFSERR_EXIST", 6 },
  { "NFSERR_FBIG", 10 },
  { "NFSERR_IO", 3 },
  { "NFSERR_ISDIR", 9 },
  { "NFSERR_NAMETOOLONG", 13 },
  { "NFSERR_NODEV", 7 },
  { "NFSERR_NOENT", 2 },
  { "NFSERR_NOSPC", 11 },
  { "NFSERR_NOTDIR", 8 },
  { "NFSERR_NOTEMPTY", 14 },
  { "NFSERR_NXIO", 4 },
  { "NFSERR_PERM", 1 },
  { "NFSERR_ROFS", 12 },
  { "NFSERR_STALE", 16 },
  { "NFSERR_WFLUSH", 17 },
  { "NFS_OK", 0 },
};
const ProtobufCEnumDescriptor nfs__stat__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nfs.Stat",
  "Stat",
  "Nfs__Stat",
  "nfs",
  18,
  nfs__stat__enum_values_by_number,
  18,
  nfs__stat__enum_values_by_name,
  11,
  nfs__stat__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue nfs__ftype__enum_values_by_number[6] =
{
  { "NFNON", "NFS__FTYPE__NFNON", 0 },
  { "NFREG", "NFS__FTYPE__NFREG", 1 },
  { "NFDIR", "NFS__FTYPE__NFDIR", 2 },
  { "NFBLK", "NFS__FTYPE__NFBLK", 3 },
  { "NFCHR", "NFS__FTYPE__NFCHR", 4 },
  { "NFLNK", "NFS__FTYPE__NFLNK", 5 },
};
static const ProtobufCIntRange nfs__ftype__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex nfs__ftype__enum_values_by_name[6] =
{
  { "NFBLK", 3 },
  { "NFCHR", 4 },
  { "NFDIR", 2 },
  { "NFLNK", 5 },
  { "NFNON", 0 },
  { "NFREG", 1 },
};
const ProtobufCEnumDescriptor nfs__ftype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "nfs.FType",
  "FType",
  "Nfs__FType",
  "nfs",
  6,
  nfs__ftype__enum_values_by_number,
  6,
  nfs__ftype__enum_values_by_name,
  1,
  nfs__ftype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
