name: Mount and Nfs Server CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo ./install_dependencies

      - name: Build Server
        run: make all
      - name: Build Tests
        run: make test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./build
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: build

      - name: Build Docker Images
        run: tests/build_images

      - name: Run Tests
        run: tests/run_tests
