name: Mount and Nfs Server Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build docker images
        run: tests/build_images.sh
      - name: Run tests
        run: tests/run_tests.sh
